---
- name: test create file, directory, and copy the file
  hosts: all
  tasks:
    - name: Define local variables
      ansible.builtin.set_fact:
        _src_dir: /opt/copy_test/
        _src_file: 10001_Linux_Installer_kaihatsu.zip

    - name: copy 
      ansible.builtin.copy:
        src: "./{{ _src_file }}"
        dest: /tmp
      

        

