---
- name: Verify file consistency in EE using get_url and copy
  hosts: all
  gather_facts: false
  vars:
    _src_url: https://www.gnu.org/licenses/gpl-3.0.txt
    _src_file: sample.txt
  tasks:

    - name: Download file inside EE (コンテナ)
      ansible.builtin.get_url:
        url: "{{ _src_url }}"
        dest: "./{{ _src_file }}"
      delegate_to: localhost

    - name: SHA256 on EE
      ansible.builtin.command: "sha256sum ./{{ _src_file }}"
      register: sha_local
      delegate_to: localhost

    - name: Copy file to target
      ansible.builtin.copy:
        src: "./{{ _src_file }}"
        dest: "/tmp/"
      delegate_to: localhost

    - name: SHA256 on target
      ansible.builtin.command: "sha256sum /tmp/{{ _src_file }}"
      register: sha_target

    - name: Compare hashes
      ansible.builtin.debug:
        msg: |
          ✅ SHA256 Comparison
          EE:      {{ sha_local.stdout }}
          Target:  {{ sha_target.stdout }}
